# Generated by Django 5.1.3 on 2024-11-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideojuegoRetro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_lanzamiento', models.DateField()),
                ('genero', models.CharField(max_length=100)),
                ('plataforma', models.CharField(max_length=100)),
                ('portada', models.FileField(upload_to='videojuegos/')),
            ],
        ),
    ]
